version: 0.2
phases:
  install:
    commands:
      - aws cloudformation delete-stack 
        --stack-name ${PROJECT_DEPLOYMENT_NAME}-deploy
      - aws cloudformation delete-stack
        --stack-name ${PROJECT_DEPLOYMENT_NAME}-network